<a href="https://colab.research.google.com/github/venkatanaresh4285/Data-Science/blob/main/1_Numpy1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [7]:
!pip install numpy


In [2]:
import numpy as np

In [10]:
lst=[[1,2,3],
     [2,3,4],
     [4,5,6]]
print(lst)
print(type(lst))

[[1, 2, 3], [2, 3, 4], [4, 5, 6]]
<class 'list'>


In [11]:
arr=np.array(lst)

In [12]:
arr

array([[1, 2, 3],
       [2, 3, 4],
       [4, 5, 6]])

In [13]:
type(arr)

numpy.ndarray

In [14]:
arr.ndim

2

In [15]:
arr.shape

(3, 3)

In [16]:
arr.size

9

In [17]:
arr.dtype

dtype('int64')

In [20]:
zeros=np.zeros((3,5))

In [21]:
zeros

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [22]:
ones=np.ones((6,3))

In [23]:
ones

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])