<a href="https://colab.research.google.com/github/venkatanaresh4285/Data-Science/blob/main/2Numpyarithmetic.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
import numpy as np

a=np.array([2,3,4,5,6])
b=np.array([5,6,7,8,9])

ans=a+b


In [4]:
ans

array([ 7,  9, 11, 13, 15])

In [12]:
ans=np.add(a,b)
print(ans)

[ 7  9 11 13 15]


In [13]:
c=np.array([1,3,5,7,9])
ans=a+b+c
print(ans)

[ 8 12 16 20 24]


In [14]:
ans=np.add(a,b,c)
print(ans)

[ 7  9 11 13 15]


In [22]:
#This is Subtraction using numpy
import numpy as np
a=np.array([5,6,7,8,9])
b=np.array([1,3,5,7,9])
# here We subtracted using operator
ans_sb=a-b
print(ans_sb)
#We have a function called subtract in array
ans_sb=np.subtract(a,b)
print(ans_sb)

c=np.array([1,2,3,4,5])
ans_sb=a-b-c
print(ans_sb)


[4 3 2 1 0]
[4 3 2 1 0]
[ 3  1 -1 -3 -5]


In [27]:
#This is multiplication of arrays using numpy
import numpy as np
a=np.array([1,2,3,4,5])
b=np.array([2,3,4,5,6])

ans_ml=a*b
print(ans_ml)

#We can multiply using the multiply method available in numpy
ans_ml=np.multiply(a,b)
print(ans_ml)


[ 2  6 12 20 30]
[ 2  6 12 20 30]


In [30]:
#This is division of elemenets using Numpy
import numpy as np
a=np.array([1,2,3,4,5])
b=np.array([3,4,5,6,7])
ans_d=a/b
print(ans_d)

ans_d=np.divide(a,b)
print(ans_d)

[0.33333333 0.5        0.6        0.66666667 0.71428571]
[0.33333333 0.5        0.6        0.66666667 0.71428571]


In [31]:
#This is finding maximum and minimum element using numpy in one dimensional array
import numpy as np
a=np.array([1,2,3,4,5])
b=np.array([4,5,6,7,8])

maxia=np.max(a)
maxib=np.max(b)
minia=np.min(a)
minib=np.min(b)

print("Maximum element in the Array a is: ",maxia)
print("Maximum element in Arrray b is : ",maxib)
print("Minimum element in the Arrray a is : ",minia)
print("Minimum element in Arrray b is :",minib)

Maximum element in the Array a is:  5
Maximum element in Arrray b is :  8
Minimum element in the Arrray a is :  1
Minimum element in Arrray b is : 4


In [33]:
import numpy as np
a=np.array([[1,2,3],
            [4,5,6],
            [7,8,9]])
print("Minimum element int the array is : ",np.min(a))
print("Maximum element in the array is :",np.max(a))

Minimum element int the array is :  1
Maximum element in the array is : 9


In [35]:
import numpy as np
a=np.array([[1,2,3],
            [4,5,6],
            [10,11,13]])

max_col=np.max(a,0)
max_row=np.max(a,1)
min_col=np.min(a,0)
min_row=np.min(a,1)

print("Maximum element in the column is : ",max_col)
print("Maximum element in the row is    : ",max_row)
print("Minimum element in the column is : ",min_col)
print("Minimum element in the column is : ",min_row)

Maximum element in the column is :  [10 11 13]
Maximum element in the row is    :  [ 3  6 13]
Minimum element in the column is :  [1 2 3]
Minimum element in the column is :  [ 1  4 10]
