<a href="https://colab.research.google.com/github/venkatanaresh4285/Data-Science/blob/main/3_Numpysort_ipyn.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np


In [ ]:
a=np.array([[10,15],
            [12,1]])
print("Sorting though columns ",np.sort(a,axis=0))

The sort of given a is  [[10  1]
 [12 15]]


In [ ]:
a=np.array([[20,10],[23,12]])
print("Sorting through rows ",np.sort(a,axis=-1))

Sorting through rows  [[10 20]
 [12 23]]


In [ ]:
a=np.array([[20,10],[23,12]])
print("Sorting through rows ",np.sort(a,axis=None))

Sorting through rows  [10 12 20 23]


In [1]:
import numpy as np
arr = np.array([[7,3,8,6,4], [7,2,9,8,6],[5,4,2,3,1]])
print(np.sort(arr , axis = 1, kind = 'mergesort'))
print()
print(np.sort(arr , axis = 0, kind = 'quicksort'))
print()
print(np.sort(arr , kind = 'heapsort'))

[[3 4 6 7 8]
 [2 6 7 8 9]
 [1 2 3 4 5]]

[[5 2 2 3 1]
 [7 3 8 6 4]
 [7 4 9 8 6]]

[[3 4 6 7 8]
 [2 6 7 8 9]
 [1 2 3 4 5]]
