<a href="https://colab.research.google.com/github/venkatanaresh4285/Data-Science/blob/main/4_Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import numpy as np
arr=np.array([1,2,3,4])
arr2=np.array([5,6,7,8])
print("The elements after merging is ",np.vstack((arr,arr2)))

The elements after merging is  [[1 2 3 4]
 [5 6 7 8]]


In [3]:
arr1=np.array([[1,3,5,7,9],
               [2,3,4,5,6]])
arr3=np.array([[3,4,5,6,7],
               [1,2,5,7,3]])
print("Merging though horizantal",np.hstack((arr1,arr3)))

Merging though horizantal [[1 3 5 7 9 3 4 5 6 7]
 [2 3 4 5 6 1 2 5 7 3]]


In [21]:
np.concatenate((arr1,arr3),axis=0)

array([[1, 3, 5, 7, 9],
       [2, 3, 4, 5, 6],
       [3, 4, 5, 6, 7],
       [1, 2, 5, 7, 3]])

In [12]:
np.concatenate((arr1,arr3),axis=1)

array([[1, 3, 5, 7, 9, 3, 4, 5, 6, 7],
       [2, 3, 4, 5, 6, 1, 2, 5, 7, 3]])

In [26]:
np.hsplit(arr1,1)

[array([[1, 3, 5, 7, 9],
        [2, 3, 4, 5, 6]])]

In [29]:
np.vsplit(arr3,2)

[array([[3, 4, 5, 6, 7]]), array([[1, 2, 5, 7, 3]])]

In [30]:
import numpy as np


In [32]:
sl=np.array([1,3,4,5,6,7,8,9,10])
print(sl[3:-3])

[5 6 7]


In [35]:
sl_2=np.array([[1,2,3,4,5],
               [3,4,5,6,7],
               [5,6,7,8,9],
               [1,2,3,7,3]])

In [42]:
sl_2[: 2 , :2]

array([[1, 2],
       [3, 4]])

In [43]:
sl_2[1,2]

5

In [44]:
sl_2[2,4]

9

In [45]:
sl_2[1: ,1:]#removing the first row and first column

array([[4, 5, 6, 7],
       [6, 7, 8, 9],
       [2, 3, 7, 3]])

In [46]:
sl_2[: 1,:1]#it prints only first row first column element

array([[1]])

In [ ]:
import numpys as np


In [48]:
#counting elements using list
count=0
lst=[1,2,3,4,5,6,7,8,9,10]
for i in lst:
  if(i>5):
    count+=1
print(count)

5


In [49]:
lst=np.array([1,2,3,4,5,6,7,8,9,10])

In [50]:
lst>5

array([False, False, False, False, False,  True,  True,  True,  True,
        True])

In [51]:
lst[lst>5]

array([ 6,  7,  8,  9, 10])

In [52]:
len(lst[lst>5])

5

In [53]:
len(lst[lst%3==0])

3

In [54]:
lst[lst%3==0]

array([3, 6, 9])